module Constants
    CATEGORIES = [
        "critical_area_buffer",
        "forest_conservation",
        "meadow_restoration",
        "reforestation",
        "specimen_tree",
        "stream_buffer",
        "tree_protection",
        "wetland",
    ]

    MARYLAND_COUNTIES = [
        "Allegany County",
        "Anne Arundel County",
        "Baltimore County",
        "Baltimore City",
        "Calvert County",
        "Caroline County",
        "Carroll County",
        "Cecil County",
        "Charles County",
        "Dorchester County",
        "Frederick County",
        "Garrett County",
        "Harford County",
        "Howard County",
        "Kent County",
        "Montgomery County",
        "Prince George's County",
        "Queen Anne's County",
        "Somerset County",
        "St. Mary's County",
        "Talbot County",
        "Washington County",
        "Wicomico County",
        "Worcester County",
    ]

    VIRGINIA_PLACES = [
        "Arlington, VA",
        "Alexandria, VA",
        "Fairfax, VA",
    ]

    STATES = [
        "AK",
        "AL",
        "AR",
        "AZ",
        "CA",
        "CO",
        "CT",
        "DC",
        "DE",
        "FL",
        "GA",
        "HI",
        "IA",
        "ID",
        "IL",
        "IN",
        "KS",
        "KY",
        "LA",
        "MA",
        "MD",
        "ME",
        "MI",
        "MN",
        "MO",
        "MS",
        "MT",
        "NC",
        "ND",
        "NE",
        "NH",
        "NJ",
        "NM",
        "NV",
        "NY",
        "OH",
        "OK",
        "OR",
        "PA",
        "RI",
        "SC",
        "SD",
        "TN",
        "TX",
        "UT",
        "VA",
        "VT",
        "WA",
        "WI",
        "WV",
        "WY"
    ]
end